import { Collections } from "@/lib/products";
import { hashSync } from "bcrypt-ts-edge";


const sampleData = {
  users: [
    {
      name: 'John Doe',
      email: 'admin@example.com',
      password: hashSync('Fakepassword@123', 10),
      role: 'admin',
    },
    {
      name: 'Jane Smith',
      email: 'user@example.com',
      password: hashSync('Fakepassword@123', 10),
      role: 'user',
    },
  ],
  products: [
    {
      id: "16e30809-fac2-496b-bb85-b1a98ad07757",
      name: "The Windsor Suit",
      slug: "the-windsor-suit",
      category: "TLR RTW Smart Casual",
      price: 3800,
      images: [
        "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=1200&h=1600&fit=crop",
        "https://images.unsplash.com/photo-1593030103066-0093718e3d49?w=1200&h=1600&fit=crop",
        "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1200&h=1600&fit=crop",
      ],
      description: "Classic three-piece elegance",
      longDescription: "The Windsor Suit represents the pinnacle of traditional British tailoring, reimagined for the modern gentleman. Each suit is meticulously handcrafted over 80+ hours by our master tailors, featuring a full canvas construction that moulds to your body over time. The three-piece design includes a single-breasted jacket with notch lapels, a matching waistcoat, and expertly pleated trousers.",
      features: [
        "Full canvas construction",
        "Hand-finished buttonholes",
        "Surgeon's cuffs with working buttons",
        "Pick-stitched lapels and edges",
        "Interior monogram available",
        "Lifetime alterations included",
      ],
      materials: [
        "Super 150s Merino wool from Loro Piana",
        "Bemberg silk lining",
        "Mother-of-pearl buttons",
        "Real horn buttons optional",
      ],
      deliveryTime: "8-10 weeks",
      popularity: 95,
      rating: 4.8,
      numReviews: 0,
      stock: 10,
    },
    {
      id: "3be518a8-a92f-4ba3-a73c-d20d43e331f3",
      name: "The Mayfair Blazer",
      slug: "the-mayfair-blazer",
      category: "TLR RTW Native",
      price: 1950,
      images: [
        "https://images.unsplash.com/photo-1593030103066-0093718e3d49?w=1200&h=1600&fit=crop",
        "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=1200&h=1600&fit=crop",
        "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=1200&h=1600&fit=crop",
      ],
      description: "Refined casual sophistication",
      longDescription: "The Mayfair Blazer bridges the gap between formal and casual with effortless sophistication. This versatile piece features a half-canvas construction for comfort and structure, making it ideal for both business meetings and weekend gatherings. The slightly softened shoulder and patch pockets lend a relaxed elegance while maintaining impeccable lines.",
      features: [
        "Half-canvas construction",
        "Soft shoulder construction",
        "Patch pockets with flaps",
        "Double vents for movement",
        "Interior card pockets",
        "Complimentary first alteration",
      ],
      materials: [
        "Super 120s wool-cashmere blend",
        "Cupro lining for breathability",
        "Corozo nut buttons",
        "Melton undercollar",
      ],
      deliveryTime: "6-8 weeks",
      popularity: 88,
      rating: 4.8,
      numReviews: 0,
      stock: 10,
    },
    {
      id: "44543d45-6e62-4b13-84cd-f437a07aa4e5",
      name: "The Savile Overcoat",
      slug: "the-savile-overcoat",
      category: "TLR RTW Native",
      price: 4200,
      images: [
        "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=1200&h=1600&fit=crop",
        "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=1200&h=1600&fit=crop",
        "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=1200&h=1600&fit=crop",
      ],
      description: "Timeless winter luxury",
      longDescription: "The Savile Overcoat is the definitive statement piece for colder months, crafted in the tradition of the finest British outerwear. Cut generously to layer over suits while maintaining an elegant silhouette, this coat features a fly front for clean lines and deep welt pockets for practicality. The peak lapels add a touch of formality befitting its heritage.",
      features: [
        "Full-length fly front closure",
        "Deep welt pockets with flaps",
        "Interior security pocket",
        "Chain hanger loop",
        "Center back vent",
        "Hand-stitched pick stitching",
      ],
      materials: [
        "100% cashmere from Colombo",
        "Heavy silk twill lining",
        "Horn buttons",
        "Real melton undercollar",
      ],
      deliveryTime: "10-12 weeks",
      popularity: 75,
      rating: 4.8,
      numReviews: 0,
      stock: 10,
    },
    {
      id: "5390595e-9bb2-4f16-bb85-b66d72c37eb5",
      name: "The Kensington Shirt",
      slug: "the-kensington-shirt",
      category: Collections.ACCESSORIES,
      price: 450,
      images: [
        "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=1200&h=1600&fit=crop",
        "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=1200&h=1600&fit=crop",
        "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=1200&h=1600&fit=crop",
      ],
      description: "Impeccable detail",
      longDescription: "The Kensington Shirt exemplifies the art of luxury shirtmaking with precision sizing ensuring a perfect fit. Each shirt features single-needle stitching throughout, hand-sewn buttonholes, and elegant collar styling. The shirts are cut from the finest two-fold cotton fabrics, offering both comfort and longevity.",
      features: [
        "Single-needle construction",
        "Hand-sewn buttonholes",
        "Mother-of-pearl buttons",
        "Removable collar stays",
        "Split back yoke",
        "Gussetted side seams",
      ],
      materials: [
        "Thomas Mason two-fold poplin",
        "Sea Island cotton available",
        "Swiss cotton options",
        "Aluminium collar stays",
      ],
      deliveryTime: "3-4 weeks",
      popularity: 82,
      rating: 4.8,
      numReviews: 0,
      stock: 10,
    },
    {
      id: "6b9b1e2b-7484-4fd7-8892-c2352ecb87f1",
      name: "The Chelsea Trousers",
      slug: "the-chelsea-trousers",
      category: "Accessories",
      price: 680,
      images: [
        "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=1200&h=1600&fit=crop",
        "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=1200&h=1600&fit=crop",
        "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=1200&h=1600&fit=crop",
      ],
      description: "Perfect fit, perfect form",
      longDescription: "The Chelsea Trousers represent the foundation of a well-dressed gentleman's wardrobe. Cut with a medium rise and gentle taper, these trousers drape beautifully while allowing freedom of movement. Features include a traditional extended waistband with side adjusters, eliminating the need for a belt, and a French fly closure for a clean front.",
      features: [
        "Extended waistband closure",
        "Side adjusters for fit",
        "French bearer fly",
        "Slant front pockets",
        "Double-jetted back pockets",
        "Curtained waistband",
      ],
      materials: [
        "Super 130s worsted wool",
        "Cotton twill pocketing",
        "Corozo buttons",
        "Real horn buttons optional",
      ],
      deliveryTime: "4-5 weeks",
      popularity: 79,
      rating: 4.8,
      numReviews: 0,
      stock: 10,
    },
    {
      id: "7b36d1a0-5e2c-443e-a4e1-d62b334299fa",
      name: "The Belgravia Tuxedo",
      slug: "the-belgravia-tuxedo",
      category: "TLR RTW Smart Casual",
      price: 5200,
      images: [
        "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1200&h=1600&fit=crop",
        "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=1200&h=1600&fit=crop",
        "https://images.unsplash.com/photo-1593030103066-0093718e3d49?w=1200&h=1600&fit=crop",
      ],
      description: "Black tie excellence",
      longDescription: "The Belgravia Tuxedo is the ultimate expression of evening elegance, designed for those moments that demand nothing less than perfection. Featuring a shawl collar faced in silk grosgrain, single button closure, and satin-striped trousers, this tuxedo adheres to the most traditional standards while incorporating modern comfort. Each detail, from the silk-covered buttons to the jetted pockets with silk piping, speaks to our commitment to excellence.",
      features: [
        "Full canvas construction",
        "Silk grosgrain shawl collar",
        "Silk-covered buttons",
        "Jetted pockets with silk piping",
        "Satin stripe on trousers",
        "Black tie bow tie included",
      ],
      materials: [
        "Super 180s midnight blue wool",
        "100% silk facing",
        "Heavy satin lining",
        "Genuine silk braiding",
      ],
      deliveryTime: "10-12 weeks",
      popularity: 91,
      rating: 4.8,
      numReviews: 0,
      stock: 10,
    },
  ],
  shippingAddressDefaultValues: [
    {
      fullName: "Alice Johnson",
      streetAddress: "42 Elm Street",
      city: "Springfield",
      postalCode: "12345",
      country: "USA",
      lng: "-93.2923",
      lat: "44.9537",
    },
    {
      fullName: "Mohammed Al-Fulan",
      streetAddress: "12 Palm Grove Avenue",
      city: "Lagos",
      postalCode: "101001",
      country: "Nigeria",
      lng: "3.3792",
      lat: "6.5244",
    },
    {
      fullName: "Emma Zhang",
      streetAddress: "88 Blossom Road",
      city: "Shanghai",
      postalCode: "200000",
      country: "China",
      lng: "121.4737",
      lat: "31.2304",
    },
    {
      fullName: "Lucas Müller",
      streetAddress: "9 Berliner Strasse",
      city: "Berlin",
      postalCode: "10115",
      country: "Germany",
      lng: "13.4050",
      lat: "52.5200",
    },
  ],

};

export default sampleData;
